# wrangler.toml
name              = "hrportallogin"
main              = "./index.js"   # path to your Worker script
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# If you do NOT ship any static files, delete the whole [assets] section.
# directory = "./dist"
